apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       # Temporarily allows 1 extra pod to be created
      maxUnavailable: 1 # Ensures no pods are taken offline before new ones are ready
  replicas: 5
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      containers:
      - name: myapp3
        image: nginx
        ports:
        - containerPort: 80
    volumeMounts:
    - name: hostpath-storage
      mountPath: /data
    volumes:
     - name: hostpath-storage
       persistentVolumeClaim:
         claimName: my-hostpath-pvc

