apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: database
  labels:
    app: my1stapp
spec:
  containers:
  - name: myapp
    image: mariadb
    # env:
    #  - name: MARIADB_ROOT_PASSWORD
    #    valueFrom:
    #       configMapKeyRef:
    #         name: myvariable
    #         key: MARIADB_ROOT_PASSWORD
    #  - name: department
    #    valueFrom:
    #       configMapKeyRef:
    #         name: myvariable
    #         key: department
    envFrom:
      - configMapRef:
          name: myvariable

    ports:
      - containerPort: 80
