apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: database
  labels:
    app: my1stapp
spec:
  containers:
  - name: myapp
    image: mariadb
    env:
     - name: MARIADB_ROOT_PASSWORD
       valueFrom:
          secretKeyRef:
            key: password
     - name: department
       valueFrom:
          configMapKeyRef:
            name: myvariable
            key: department
    ports:
      - containerPort: 80
