apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
  - name: my-container
    image: mariadb
  env:
    - name: MARIADB_ROOT_PASSWORD
      value: admin123
    volumeMounts:
    - name: hostpath-storage
      mountPath: /usr/local/apache2/htdocs
  
  volumes:
  - name: hostpath-storage
    persistentVolumeClaim:
      claimName: my-hostpath-pvc
